### PR TITLE
Alternative ground station setup

### PR DESCRIPTION
**Pull request by FoeFear**
-Adds ion station to the game.
-Targeting for ion is set to air units only, it is no longer has interchangeable targeting

### CODE REVIEW

**Comment by FoeFear** [comment]
I am now having a dilemma on whether or not if i should remove the prefabs containing the ion station (and remove the station from wc) and just have the sprites and the weapon setup for future use since you wanted to have that idea setup.

If you want me to remove the prefabs and have the sprites only, just say the word.

**Comment by rudderbucky** [comment]
I think I would slightly prefer not having it, but there is precedent for redundant items (i.e. the mission control)

**Comment by FoeFear** [comment]
Could you explain a bit more, i don't i understood what you mean. 

If i'm getting this correct, are you saying that you prefer more alternative items (the sprites) than actual blueprints?

**Comment by rudderbucky** [comment]
That's right. Also, is the ion station shell added as a resource here?

**Comment by FoeFear** [comment]
The sprite, yes it is still in here. If you are talking about the shell in the default resources, I removed it. Wasn't really sure what had to be removed. I'll bring it back.

**Comment by rudderbucky** [comment]
Go ahead and bring it back as a default resource

**Comment by FoeFear** [comment]
Got that fixed.

**Pull request merged**
