### PR TITLE
Semi-Core

### PR DESCRIPTION
**Pull request by FoeFear**
I have added the Semi-Core to the game (even though they have default stats). This does work and loads properly. 

-Adding the semi-core to the game
-Switched the cores for light core, block core, and super light core to have semi-cores

### CODE REVIEW

**Comment by FoeFear** [comment]
There is another way to prevent people from upgrading the core. I could cut out the script for the core upgrader and the add the other bit of script to the ship builder instead. I could do that but I think you should decide which would be better.

**Comment by rudderbucky** [comment]
This code is messy and I also don't want semi cores in the main world.

**Comment by FoeFear** [comment]
Yeah, i should of removed some of the code that i put the "//" instead. However, why don't you want semi-cores in the main world?

**Comment by rudderbucky** [comment]
They weren't a significant part of the story in the original game, to the point where I didn't even notice they were separate until after I read the wiki. I don't think replacing them with tier 1 cores causes any significant balancing problems either, so there really isn't any reason for them to be in the main story. I would be fine with adding them in in the WC but they shouldn't be part of the upgrade chain and should definitely not be called "core0" internally.

**Comment by FoeFear** [comment]
Ok, i think i can change that then but i'll do that in a different pull request since this one was a bit messy.

**Pull request closed without merging**
