### PR TITLE
Default Resources Reorganized

### PR DESCRIPTION
**Pull request by FoeFear**
I figured that the default resourses might needed to be reorganized. It is quite difficult when finding certain files in that asset.

### CODE REVIEW

**Comment by FoeFear** [comment]
Really weird for what just happened but, I think I fixed it

**Comment by FoeFear** [comment]
Just to make a note on this pull request. This technically does not change anything. This just organizes the file. Having this file organized would make it easier to manage meta files, audio clips, parts, etc.

**Comment by rudderbucky** [comment]
This is subjective, not to mention unnecessary since I've got internal tools and it's not something players will deal with.

**Comment by FoeFear** [comment]
Oh, ok then

**Pull request closed without merging**
