### PR TITLE
Shooter Sprites Update (Fix)

### PR DESCRIPTION
**Pull request by FoeFear**
Update the ability shooters and indicators with a couple of new sprites.
-updated shooters for the beam and siege tanks
-six additional ability indicators for specific abilities (can be altered any way you want)
-bomb shooter sprite replaces the missile shooter sprite
-secondary data is usable for the new beam and siege shooter sprites, and the old style of the siege shooter (use beamgroundshooter_sprite, siegegroundshooter_sprite and siegeshooter_sprite)

I have tested this out and I pretty certain that it works. (I have fixed it so that this is now a branch instead of it being a master.)

### CODE REVIEW

**Comment by rudderbucky** [comment]
The shooter resource name strings need to be more descriptive than just numbers.

**Comment by FoeFear** [comment]
I think I could put "ground" to replace the numbers in the shooter sprites and some sort of short name (or code) for the indicators. Although, the indicators are always going to be tied to specific abilities.

So, remove the numbers and add a short code or something like that?

**Comment by rudderbucky** [comment]
I would prefer more verbosity than "tt" and "dm".

**Comment by FoeFear** [comment]
Ok, I'll change that then. This could be a quick fix.

**Comment by FoeFear** [comment]
I hope that fixes it. I don't know if there is anything else that needs to be changed.

**Comment by FoeFear** [comment]
I am not sure but should I convert this as a draft or leave the pull request the way it is?

**Pull request merged**
