### PR TITLE
Ion

### PR DESCRIPTION
**Pull request by FoeFear**
This is exactly the same as the other, it is a better version than the other pull request for ion.

### CODE REVIEW

**Comment by FoeFear** [comment]
This is supposed to be a pull request for the previous one for ion but there were some odd problems with the original branch that i had created and caused some cancerous problems with the branch and my master repository (random error 500 pop ups). I really don't know what had happened but the only thing that could have happened was probably a glitch or an error from some source in my end (but that is my theory).

**Comment by rudderbucky** [comment]
The ability is not "Ion Beam", it's just "Ion".

**Comment by FoeFear** [comment]
Oh, i'll fix that

**Comment by FoeFear** [comment]
I don't think i will add the alternate ion shooter (the station ion shooter). Not yet but another time. If i tried to put it in right now, what will it be used for as there is nothing using it at the moment. If you want me to add it in, i'm fine having it in but just let you know that nothing uses it.

**Pull request merged**
