### PR TITLE
Party Member Bugfix

### PR DESCRIPTION
**Pull request by FoeFear**
This is mainly to fix an issue related to the party member system.
- Save files will remember if the party was locked from the lock party node or from the corescripts.
- Save files will remember the party members who were currently in your party.

### CODE REVIEW

**Comment by FoeFear** [comment]
I haven't been able to get the save file to successfully load the party members after reloading your save file.

**Comment by rudderbucky** [comment]
The save file *shouldn't* remember if the party was locked, that could potentially lead to softlocks. Instead, if there are places where this matters the scripting systems should lock the party at the beginning. Save files remembering party members sounds good though.

**Comment by FoeFear** [comment]
I know there was an issue in the three battlezones where saving and quitting during that task would prevent players from adding sukrat and aristu to their party because they are disabled. And the only party member they could add is clearly delusional if they completed the clearly delusional gauntlet. I remember taking a screenshot of the person that stated it on itch.

Unfortunately, I do not know how to make the game add party members when loading the game. It only remembers which party member was previously added.

**Comment by rudderbucky** [comment]
Can you force clear the party and add Sukrat/Aristu at the appropriate checkpoints during the mission?

**Comment by FoeFear** [comment]
I don't know what you mean by force clearing the party.

I know that you can't add party members when the lock is enabled during that part of the mission. But if players save and quit during after that checkpoint, they would be able to add any party members. If they chose the other option (to fight the battlezones solo), they wouldn't be able to add Sukrat or Aristu, but would be able to add Clearly Delusional.

https://youtu.be/J3bex_1AO2U

**Comment by rudderbucky** [comment]
I'm not sure what the issue is here. If the issue is that Sukrat and Aristu are not assignable due to the party being locked, could you use a PartyManagementNode to clear the player's current party, and add Sukrat and Aristu at each appropriate checkpoint? If the issue is the party cannot be modified upon reaching haven 4, any reason why you can't unlock the party there?

**Comment by FoeFear** [comment]
Odd. I looked into the canvas, and I could have sworn there was a party member availability node prior to entering Haven 4.

Ether way, the main issue i'm trying to explain is mainly how the lock party and party members currently work. Because the game does not have a way to save any configurations related to whether the party is currently locked, and know which party members that were previously in the player's party, players can add any party member after exiting and re-entering the game. That is what I'm trying to say.

This second video should explain a bit more. It doesn't show it, but I had chosen the option to fight the battlezones solo.
https://youtu.be/AL8WS4LWn4U

Adding a party management node for each checking during that part of the tasks can fix the issue, but it wouldn't be a good solution.

**Comment by rudderbucky** [comment]
Why wouldn't it be a good solution? The game should only save values which need to be saved, like checkpoints, credits or parts. If you can derive information from saved information, such as whether the party should be locked, it should instead be done via corescripts/a canvas.

If the concern is the repetitiveness of the task, corescripts helps alleviate this with functions, or you could try using triggers in a canvas.

**Comment by FoeFear** [comment]
It's because I don't want to re-run the same functions multiple times whether by trigger nodes or corescripts. It adds more space and clutters the canvases/corescripts. Just having one function to control and execute it is enough.

**Comment by rudderbucky** [comment]
It's not clutter if the functionality is useful. If the mission would need to be modified for whatever reason it would be additional work to migrate the save. I'm fine with remembering party members in the save though so I'll accept a PR with just that.

**Comment by FoeFear** [comment]
Then, I guess I'll comment out the lock party parts. You can add them in if you want to. But from what I remember when I tested it, it shouldn't cause any issues given that the default value is false.

Just note that currently, the game can remember which party member was in the player's party, but i am unable to get the game to add the party members into the player's party when they open their save file.

**Comment by rudderbucky** [comment]
So it doesn't actually do anything with the saved data? Not worth a PR unless it can do that as well IMO.

**Comment by FoeFear** [comment]
Then there is nothing else I can do

**Comment by FoeFear** [comment]
Closing it due to it being messy and me unable to remember the scripts used to get it to work. Might try a new Pull Request if possible.

**Pull request closed without merging**
