### PR TITLE
Ground combat bandaid

### PR DESCRIPTION
**Pull request by BaegEhl**
battlezone AI now properly prioritizes tanks to use
-if enemy has more tanks, AI will prioritize laser/beam -> bullet -> speeder
-if enemy has more ground presence overall, AI will prioritize siege/beam -> bullet -> speeder
-if neither of these are true, AI will prioritize missile -> laser to kill enemy air units
battlezone AI still does not actually seek out bunkers to spawn tanks, but idk how to fix that

### CODE REVIEW

**Comment by BaegEhl** [comment]
AI will now seek out bunkers when they have enough power to spawn a tank combo

**Review by Ormanus — CHANGES_REQUESTED** [review]
Sorry for taking so long! 
I tested the AI a few times and looked at the code. Here's what I found:

Other factions aren't always enemies. To reliably determine hostile tank and bunker counts, use `FactionManager.IsAllied`

That same part of code also searches through the whole entity list four times. It looks like those loops could be combined into one. 

While testing in the Upper Battle Zone, AI agents successfully bought harvester turrets but dropped them too soon afterwards, leaving small piles of them next to outposts, which were not near any power rocks. 
Most battle zones have outposts next to power rocks, and this won't be such a huge issue, but please fix this if you have time to take a look at it.

**Comment by BaegEhl** [comment]
> Sorry for taking so long!
> I tested the AI a few times and looked at the code. Here's what I found:
> 
> Other factions aren't always enemies. To reliably determine hostile tank and bunker counts, use `FactionManager.IsAllied`
> 
> That same part of code also searches through the whole entity list four times. It looks like those loops could be combined into one.
> 
> While testing in the Upper Battle Zone, AI agents successfully bought harvester turrets but dropped them too soon afterwards, leaving small piles of them next to outposts, which were not near any power rocks.
> Most battle zones have outposts next to power rocks, and this won't be such a huge issue, but please fix this if you have time to take a look at it.

Alright, i'll get to fixing this.
I think redundant looping was because  I was testing stuff and forgot to remove it afterwards
Harvester turrets were rudderbucky's job, I don't know how they work and I don't think I changed them at all

**Comment by Ormanus** [comment]
My bad! I didn't remember harvesters were added earlier... Should have noticed that when I was reading through the code. Then there's only those couple technical issues. In action it worked well enough, I saw the tanks you mentioned around the right times.

**Comment by BaegEhl** [comment]
> My bad! I didn't remember harvesters were added earlier... Should have noticed that when I was reading through the code. Then there's only those couple technical issues. In action it worked well enough, I saw the tanks you mentioned around the right times.

should be fixed now, thanks!

**Review by Ormanus — APPROVED** [review]

**Pull request merged**
