### PR TITLE
Removed fixedDeltaTime, exposed Tractor strength.

### PR DESCRIPTION
**Pull request by Starficz**

### CODE REVIEW

**Review by rudderbucky — CHANGES_REQUESTED** [review]
I can think of a few places where FDT might change, like if the game slows down due to performance issues. In any case it doesn't hurt to include FDT since as you said it doesn't change. It would probably be better to just switch the tractor forces to direct velocity changes as I said.

**Comment by Starficz** [comment]
You can't use direct velocity changes, the issue with that is by overwriting the velocity or position directly, nothing else can move the object when you are tractoring. This is very obvious when inverse tractoring as wasd on longer work when writing to velocity or position.

**Comment by rudderbucky** [comment]
You don't have to overwrite velocity I don't think, merely increase it in the direction the force currently works toward

**Comment by Starficz** [comment]
That might work with position, not velocity though as adding velocity would happen every tick, leading to runaway speed

**Comment by Starficz** [comment]
Ok, just tested, updating postion directly does get what you expect, the only issue is camera script relies on velocity checks to see if the core is moving to lock the camera. Directly updating postion messes with that. I think the best way forward is to just leave this code as is.

**Comment by rudderbucky** [comment]
Between drag and the formula-based addition to velocity I don't think it would lead to "runaway speed".

**Comment by Starficz** [comment]
Just tried, you are correct, but it still leads to janky behaviour when multiple things are affecting velocity at once (like in invert tractor)

**Pull request closed without merging**
