### PR TITLE
base dialogue

### PR DESCRIPTION
**Pull request by BaegEhl**
this should cause friendly bases and carriers to scream at you in passive chat when they take too much damage
-alerts when first taking damage and at 50% and 0% shell and core HP
-will probably need to be rewritten later
-might break stuff due to my poor understanding of the code

### CODE REVIEW

**Comment by BaegEhl** [comment]
it seems to work after extensive testing, but i'll need to fix a bug first

**Comment by BaegEhl** [comment]
alright, it should be ready

**Comment by rudderbucky** [comment]
This should be implemented like it was in the original games (via the info box at the top) instead of via passive dialogue. Maybe have 20% intervals including base destroyed

**Comment by BaegEhl** [comment]
> This should be implemented like it was in the original games (via the info box at the top) instead of via passive dialogue. Maybe have 20% intervals including base destroyed

done, should use alerts every 20% + death now

**Comment by rudderbucky** [comment]
Make the messages just "Carrier at 80% shell" etc

**Comment by BaegEhl** [comment]
> Make the messages just "Carrier at 80% shell" etc

done

**Review by rudderbucky — APPROVED** [review]
I don't think the shell alerts are necessary but let's give it a shot

**Comment by rudderbucky** [comment]
Fix the merge conflicts

**Comment by BaegEhl** [comment]
it did not, in fact, fix merge conflicts; how do I do that?

**Comment by BaegEhl** [comment]
> it did not, in fact, fix merge conflicts; how do I do that?

did this work?

**Pull request merged**
