### PR TITLE
Made "i am god" not give credits

### PR DESCRIPTION
**Pull request by Colonizor48**
If i want credits ill type in the credits command. If i want to just not have to redo a tedius section due to a bug ill type i am god. I DONT WANT CREDITS THEN.

### CODE REVIEW

**Comment by FoeFear** [comment]
I'm not sure if you know this but there is the "Immortality" command that you can use.

**Comment by Colonizor48** [comment]
> 
> 
> I'm not sure if you know this but there is the "Immortality" command that you can use.

what about instakill and stuff?

**Comment by FoeFear** [comment]
The stacked damaged boost and speed aren't separate commands from what i can recall. It would depend on whether rudderbucky would want it or not.

**Comment by rudderbucky** [comment]
I am god is a cheat. If you have an issue with a bug and don't want to cheat make an issue about it.

**Comment by Colonizor48** [comment]
I did report the bug in issues. But i still want the ability to continue the game. I was able to workaround the issue though. Via doing I am god but remembering the credits i had beforehand and changing it to that. Sorry for my poor grammar and somewhat rude demeanor the past few days Ive just been tired and usually playing the game in real time while making these. So my focus hasn't been entirety on this. Plus school. But still my fault.

**Pull request closed without merging**
