### PR TITLE
Ion sprite (fix)

### PR DESCRIPTION
**Pull request by FoeFear**
-Adds ion sprite into the game

### CODE REVIEW

**Comment by FoeFear** [comment]
I feel stupid in saying this. Rudderbucky, I am sorry if I accidentally called you "rubberbucky" in the comments in one of the updates. I don't really know how many times i didn't see that but i really thought the ds were bs.

**Comment by rudderbucky** [comment]
Name sprite pngs in normal English, not in camel case (i.e., "Ion Beam.png")

**Comment by FoeFear** [comment]
I'm pretty sure I correctly renamed it

**Comment by FoeFear** [comment]
This is weird. I don't know how this happened but i cannot access the branch anymore for some reason. I was able to update the default resources but i couldn't update the ability utilities script (before getting kicked out with error 500). 

The id for ion would of been "ionbeamshooter_sprite" instead of "ionshooter_sprite". Hopefully, i can access it by tomorrow.

**Pull request closed without merging**
