### PR TITLE
add 2 new factions

### PR DESCRIPTION
**Pull request by Colonizor48**
Add 2 new factions for future use. The cyan ancients and the white forerunners.(I saw an olive faction in the game that wasn't used yet so might as well add a few more.)

### CODE REVIEW

**Comment by Colonizor48** [comment]
Sorry for the exess stuff that was just me deleting the ancient 2018 info dump from my branch

**Comment by Colonizor48** [comment]
Also here is my idea for lore. Its a bit trippy and unique but here we go regardless. The game is actually an mmorpg. Being played by humans billions of years into the future. As humans had uploaded their ocnciousnesses onto a matrioska brain like megastructure being powered by a penrose sphere around a black hole of a few hundred thousand solar masses.

**Comment by Colonizor48** [comment]
The penrose sphere would also colect energy from the x-ray jets and acresion disk of the black hole. Aswell as a system to automaticly retreve  matter from higher dimentions and using it to generate energy via the penrose process.

**Comment by Colonizor48** [comment]
And even extracting the small amounts of hawking radiation the black hole emits.

**Comment by Colonizor48** [comment]
The entire scc universe is just 1 game. Played on the black hole computer thingy.

**Comment by Colonizor48** [comment]
1 game out of milions.

**Comment by Ormanus** [comment]
Tbh, I'd like to keep this separate from any version of our world. I love
these scifi concepts and would like to see stories based on them... But
it's just not ShellCore.
Furthermore, I don't see how this would be relevant in the game's plot.

**Comment by Colonizor48** [comment]
What about the new factions tho? We could change the names later. I would atleast add the cyan faction because there is almost 100% going to be one in ep3 due to the text at the begining of ep1 and ep2

**Comment by Colonizor48** [comment]
Also is ep3 intended to be the last episode as of now?

**Comment by Ormanus** [comment]
I'm sure new factions will appear, but I wouldn't add them to the official
version just because we can. Let's see if we need them first.
Even the olive faction was added purely for testing purposes.

I don't know what the ep. 3 plot will be, so I don't know if it would be
the last one. That remains to be seen.

**Comment by Colonizor48** [comment]
Allright. Ill close this then

**Pull request closed without merging**
